# not the original
work_dir: ./work_dir/ntu60/xsub/hyperformer_joint

# feeder
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  # data_path: data/ntu60/NTU60_CS.npz
  data_path: data/ntu/NTU60_CS.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: True
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_args:
  #data_path: data/ntu60/NTU60_CS.npz
  data_path: data/ntu/NTU60_CS.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False

# model
model: model.Hyperformer.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'
  joint_label: [0, 4, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1, 2, 3, 3, 3, 2, 3, 3, 3, 1, 0, 1, 0, 1]

#optim
weight_decay: 0.0004
base_lr: 0.00025
lr_decay_rate: 0.1
step: [50, 65, 90] # fixing this because the Hyper_tiny2 model get stuck at 50 epoch, cant converge


warm_up_epoch: 5

# training
device: [0]
batch_size: 100
test_batch_size: 100
num_epoch: 140
nesterov: True
